# Generated by Django 4.2.6 on 2023-11-26 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_client_user_alter_client_phone'),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование рассылки')),
                ('mailing_time', models.TimeField(verbose_name='Время рассылки')),
                ('mailing_date', models.DateField(verbose_name='Дата рассылки')),
                ('periodicity', models.CharField(choices=[('Daily', 'Раз в день'), ('Weekly', 'Раз в неделю'), ('Monthly', 'Раз в месяц')], max_length=20, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('Started', 'В процессе'), ('Completed', 'Завершена')], default='Started', max_length=20, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(to='client.client', verbose_name='Клиенты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(max_length=30, verbose_name='Статус попытки')),
                ('server_answer', models.TextField(verbose_name='Ответ почтового сервера')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
